purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6684588
  brandStrength: 1
  lightness: 0.5035842
  brandColors:
    - '#FFFFFF'
    - '#FC016A'
    - '#D3CFC6'
    - '#EC2D72'
    - '#CB5386'
  rhythmicContrast: 0.4157706
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Gaffer
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4229391
layout_spectrum: 0
