name: Gaffer
favicon: null
layout_spectrum: 0.9839658811688423
typography_spectrum: 0.11088769510388374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.48729529744014144
  lightness: 0.2706578990910202
  saturation: 0.6345377701800317
  rhythmicContrast: 0.9653736315667629
purpose: []
